import json # Importar el módulo json para manejar la carga y manipulación de datos en formato JSON, que es el formato comúnmente utilizado para los payloads de los webhooks de Xero. Este módulo permite convertir cadenas JSON en objetos de Python y viceversa, lo que facilita el procesamiento de los datos recibidos en los webhooks y la generación de respuestas o acciones basadas en esos datos.
import os # Importar módulos necesarios para manejar la seguridad de los webhooks, como hmac para calcular la firma, hashlib para usar SHA256, y base64 para codificar la firma. Estos módulos son esenciales para validar que los webhooks recibidos realmente provienen de Xero y no han sido alterados en tránsito, lo cual es fundamental para la seguridad del servidor de webhooks.
import hmac # importar hmac para calcular la firma de los webhooks utilizando la clave secreta configurada. HMAC es un algoritmo de autenticación que se utiliza para verificar la integridad y autenticidad de los mensajes, lo que es esencial para validar que los webhooks recibidos realmente provienen de Xero y no han sido alterados en tránsito.
import hashlib # Importar hashlib para usar el algoritmo SHA256 en el cálculo de la firma de los webhooks. SHA256 es un algoritmo de hash criptográfico que se utiliza para generar un resumen único del mensaje, lo que es esencial para validar la integridad de los webhooks recibidos y asegurarse de que no han sido alterados en tránsito. Al combinar HMAC con SHA256, se puede garantizar que los webhooks sean auténticos y seguros.
import base64 # Importar base64 para codificar la firma calculada de los webhooks en formato base64, que es el formato utilizado por Xero para enviar la firma en el encabezado x-xero-signature. La codificación en base64 permite representar datos binarios (como la firma HMAC) en un formato de texto legible, lo que facilita la comparación de la firma calculada con la firma recibida en el webhook para validar su autenticidad.
import logging # Importar el módulo logging para registrar información, advertencias y errores en el servidor de webhooks. Esto es importante para monitorear el funcionamiento del servidor, detectar problemas y mantener un registro de los eventos que se procesan. Configurar el logging adecuadamente permite tener una visión clara de lo que está sucediendo en el servidor y facilita la depuración en caso de errores o comportamientos inesperados.
from fastapi import FastAPI, Request, Response, BackgroundTasks, APIRouter # Importar FastAPI para crear la aplicación web, Request para manejar las solicitudes entrantes, Response para enviar respuestas al cliente, BackgroundTasks para ejecutar tareas en segundo plano sin bloquear la respuesta al cliente, y APIRouter para la organizacon y manejo de endpoints.
from dotenv import load_dotenv # Cargar variables de entorno desde un archivo .env para configurar el servidor de webhooks. Esto permite mantener las configuraciones sensibles, como la clave secreta para validar los webhooks, fuera del código fuente y en un lugar seguro. Al usar dotenv, se puede cargar automáticamente estas variables de entorno al iniciar la aplicación, lo que facilita la configuración y el despliegue del servidor de webhooks en diferentes entornos (desarrollo, producción, etc.) sin necesidad de modificar el código.
from webhooks_processor import process_webhook_events # Importar la función process_webhook_events desde el módulo webhooks_processor para manejar el procesamiento de los eventos recibidos en los webhooks de Xero. Esta función se encargará de procesar los diferentes tipos de eventos que Xero puede enviar, como la creación o actualización de facturas, y realizar las acciones necesarias en respuesta a esos eventos. Al importar esta función, podemos delegar el procesamiento de los eventos a un módulo separado, lo que ayuda a mantener el código organizado y modular.
from websockets_processor import processor

load_dotenv() # Cargar variables de entorno desde el archivo .env
logging.basicConfig(level=logging.INFO) # Configurar el logging para mostrar información igual o mayor a INFO en la consola. Esto significa que se mostrarán mensajes de información, advertencias y errores, pero no mensajes de depuración (DEBUG). Esta configuración es adecuada para un entorno de producción o desarrollo donde se desea tener visibilidad de los eventos importantes sin saturar la salida con demasiados detalles de depuración.
logger = logging.getLogger(__name__) # Crear un logger específico para este módulo

app = FastAPI() # Crear la aplicación FastAPI
webhooks_router = APIRouter() # Crear el rauter del archivo para redirigirlo a otros archivos

WEBHOOK_KEY = os.getenv("XERO_WEBHOOK_SECRET") # Obtener la clave secreta para validar los webhooks desde las variables de entorno para verificar que vienen de Xero. Esta clave se configura en el panel de control de Xero al crear el webhook. Es importante que esta clave sea segura y no se comparta públicamente, ya que es la base para validar la autenticidad de los webhooks recibidos.
if not WEBHOOK_KEY: # Si no se encuentra la clave secreta, lanzar un error para evitar que el servidor inicie sin esta configuración crítica
    raise RuntimeError("XERO_WEBHOOK_SECRET no está configurado") # Eleva un RuntimeError si la clave secreta no está configurada, ya que es esencial para la seguridad del servidor de webhooks. Sin esta clave, el servidor no podrá validar los webhooks entrantes y podría estar expuesto a ataques maliciosos.

@app.post("/xero/webhooks") # Endpoint para recibir webhooks de Xero. Este endpoint se configura en el panel de control de Xero al crear el webhook. Es importante que este endpoint sea seguro y solo acepte solicitudes de Xero, lo cual se logra validando la firma de cada solicitud utilizando la clave secreta configurada.
async def xero_webhooks(request: Request, background_tasks: BackgroundTasks): # Función asíncrona que maneja las solicitudes POST al endpoint /xero/webhooks. Esta función se encarga de validar la firma de la solicitud para asegurarse de que proviene de Xero, luego procesa el payload del webhook en segundo plano utilizando BackgroundTasks para no bloquear la respuesta al servidor de Xero. El procesamiento del webhook se delega a la función process_webhook_events, que se encarga de manejar los diferentes tipos de eventos que Xero puede enviar.
    body = await request.body() # Leer el cuerpo de la solicitud como bytes para poder validar la firma utilizando HMAC. Es importante leer el cuerpo como bytes, ya que la validación de la firma se basa en el contenido exacto del cuerpo, incluyendo cualquier formato o codificación. Si se lee como texto, podría haber cambios en el formato que invaliden la firma, incluso si el contenido es correcto.
    signature = request.headers.get("x-xero-signature", "") # Obtener la firma enviada por Xero en el encabezado x-xero-signature. Esta firma es una cadena codificada en base64 que se genera utilizando HMAC con SHA256 y la clave secreta configurada. Es importante obtener esta firma para poder compararla con la firma que se calcula localmente utilizando el mismo método, lo que permite validar que la solicitud realmente proviene de Xero y no ha sido alterada en tránsito.

    computed_signature = base64.b64encode(
        hmac.new(WEBHOOK_KEY.encode(), body, hashlib.sha256).digest()
    ).decode() # Calcular la firma localmente utilizando HMAC con SHA256 y la clave secreta configurada. El cuerpo de la solicitud se utiliza como mensaje para el cálculo de la firma, y la clave secreta se utiliza como clave para el HMAC. El resultado del HMAC se codifica en base64 para obtener una cadena que se puede comparar con la firma enviada por Xero. Es importante que el método de cálculo de la firma sea exactamente el mismo que el utilizado por Xero, incluyendo el uso de la misma clave secreta y el mismo formato para el cuerpo, para que la validación funcione correctamente.

    if not hmac.compare_digest(signature, computed_signature): # Comparar la firma enviada por Xero con la firma calculada localmente utilizando hmac.compare_digest para evitar ataques de timing. Si las firmas no coinciden, significa que la solicitud no es auténtica o ha sido alterada, por lo que se debe rechazar la solicitud y responder con un código de estado 401 Unauthorized. Es importante rechazar las solicitudes con firmas inválidas para proteger el servidor de webhooks contra ataques maliciosos que intenten enviar datos falsos o alterar los datos legítimos.
        logger.error("Firma de webhook inválida") # Registrar un error en el log indicando que la firma del webhook es inválida. Esto es útil para monitorear y detectar posibles intentos de ataque o problemas de configuración con los webhooks. El mensaje de error incluye información sobre la firma recibida, la firma calculada y el cuerpo de la solicitud para facilitar la investigación del problema.
        logger.error("Received: %s", signature) # Registrar la firma recibida en el log para ayudar a diagnosticar problemas de validación de la firma. Esto puede ser útil para comparar con la firma calculada y entender por qué la validación falló, especialmente si hay problemas de formato o codificación en el cuerpo de la solicitud que podrían afectar el cálculo de la firma.
        logger.error("Computed: %s", computed_signature) # Registrar la firma calculada en el log para ayudar a diagnosticar problemas de validación de la firma. Esto puede ser útil para comparar con la firma recibida y entender por qué la validación falló, especialmente si hay problemas de formato o codificación en el cuerpo de la solicitud que podrían afectar el cálculo de la firma.
        logger.error("Body: %s", body.decode("utf-8")) # Registrar el cuerpo de la solicitud en el log para ayudar a diagnosticar problemas de validación de la firma. Esto puede ser útil para entender si hay problemas de formato o codificación en el cuerpo que podrían afectar el cálculo de la firma, o para detectar intentos de ataque que envíen datos maliciosos. El cuerpo se decodifica como UTF-8 para que sea legible en el log, pero es importante tener cuidado al registrar el cuerpo completo, ya que podría contener información sensible. En un entorno de producción, se podría considerar registrar solo una parte del cuerpo o utilizar un nivel de log más bajo para evitar exponer datos sensibles en los logs.
        return Response(status_code=401) # Responder con un código de estado 401 Unauthorized si la firma es inválida para indicar que la solicitud no es aceptada. Esto es importante para proteger el servidor de webhooks contra solicitudes no autorizadas o maliciosas, y para cumplir con las expectativas de seguridad al manejar webhooks.

    payload = json.loads(body) # Si la firma es válida, cargar el cuerpo de la solicitud como JSON para obtener el payload del webhook. Este payload contiene la información sobre el evento que Xero está notificando, como el tipo de evento, los recursos afectados, etc. Es importante cargar el payload como JSON para poder acceder a sus datos de manera estructurada y procesarlos adecuadamente en la función process_webhook_events.

    await processor.broadcast({
        "type": "xero_webhook",
        "data": payload
    })

    background_tasks.add_task(process_webhook_events, payload) # Agregar la tarea de procesar los eventos del webhook a BackgroundTasks para que se ejecute en segundo plano. Esto permite que el servidor responda rápidamente a Xero con un código de estado 200 OK, mientras que el procesamiento real del evento se realiza de manera asíncrona sin bloquear la respuesta. Es importante utilizar BackgroundTasks para evitar que el procesamiento del evento afecte el tiempo de respuesta al servidor de Xero, lo cual podría causar problemas si el procesamiento es lento o si hay muchos eventos llegando al mismo tiempo.

    return Response(status_code=200) # Responder con un código de estado 200 OK para indicar que el webhook fue recibido y validado correctamente. Esto es importante para que Xero sepa que la solicitud fue aceptada y no intente reenviar el webhook debido a un error de validación o de procesamiento. Al responder con 200 OK, se establece una comunicación efectiva entre Xero y el servidor de webhooks, lo que permite que los eventos se procesen de manera confiable.

# if __name__ == "__main__":
#     import uvicorn
#     from servidor.secretos import obtener_entorno

#     entorno = obtener_entorno()
#     uvicorn.run('WebHooks:app', host="127.0.0.1", port=int(entorno.PUERTO), reload=True, log_level="info")